/**
 * Países ISO 3166-1 alfa-2, con el nombre en los tres idiomas que soporta la app.
 *
 * Generado con Intl.DisplayNames y commiteado como dato: la app no puede
 * depender de que Hermes traiga los datos de Intl completos en runtime.
 */

export interface Country {
  code: string;
  flag: string;
  es: string;
  en: string;
  pt: string;
}

export const COUNTRIES: readonly Country[] = [
  { code: 'AD', flag: '🇦🇩', es: "Andorra", en: "Andorra", pt: "Andorra" },
  { code: 'AE', flag: '🇦🇪', es: "Emiratos Árabes Unidos", en: "United Arab Emirates", pt: "Emirados Árabes Unidos" },
  { code: 'AF', flag: '🇦🇫', es: "Afganistán", en: "Afghanistan", pt: "Afeganistão" },
  { code: 'AG', flag: '🇦🇬', es: "Antigua y Barbuda", en: "Antigua & Barbuda", pt: "Antígua e Barbuda" },
  { code: 'AI', flag: '🇦🇮', es: "Anguila", en: "Anguilla", pt: "Anguila" },
  { code: 'AL', flag: '🇦🇱', es: "Albania", en: "Albania", pt: "Albânia" },
  { code: 'AM', flag: '🇦🇲', es: "Armenia", en: "Armenia", pt: "Armênia" },
  { code: 'AO', flag: '🇦🇴', es: "Angola", en: "Angola", pt: "Angola" },
  { code: 'AR', flag: '🇦🇷', es: "Argentina", en: "Argentina", pt: "Argentina" },
  { code: 'AT', flag: '🇦🇹', es: "Austria", en: "Austria", pt: "Áustria" },
  { code: 'AU', flag: '🇦🇺', es: "Australia", en: "Australia", pt: "Austrália" },
  { code: 'AW', flag: '🇦🇼', es: "Aruba", en: "Aruba", pt: "Aruba" },
  { code: 'AZ', flag: '🇦🇿', es: "Azerbaiyán", en: "Azerbaijan", pt: "Azerbaijão" },
  { code: 'BA', flag: '🇧🇦', es: "Bosnia y Herzegovina", en: "Bosnia & Herzegovina", pt: "Bósnia e Herzegovina" },
  { code: 'BB', flag: '🇧🇧', es: "Barbados", en: "Barbados", pt: "Barbados" },
  { code: 'BD', flag: '🇧🇩', es: "Bangladés", en: "Bangladesh", pt: "Bangladesh" },
  { code: 'BE', flag: '🇧🇪', es: "Bélgica", en: "Belgium", pt: "Bélgica" },
  { code: 'BF', flag: '🇧🇫', es: "Burkina Faso", en: "Burkina Faso", pt: "Burquina Faso" },
  { code: 'BG', flag: '🇧🇬', es: "Bulgaria", en: "Bulgaria", pt: "Bulgária" },
  { code: 'BH', flag: '🇧🇭', es: "Baréin", en: "Bahrain", pt: "Barein" },
  { code: 'BI', flag: '🇧🇮', es: "Burundi", en: "Burundi", pt: "Burundi" },
  { code: 'BJ', flag: '🇧🇯', es: "Benín", en: "Benin", pt: "Benin" },
  { code: 'BM', flag: '🇧🇲', es: "Bermudas", en: "Bermuda", pt: "Bermudas" },
  { code: 'BN', flag: '🇧🇳', es: "Brunéi", en: "Brunei", pt: "Brunei" },
  { code: 'BO', flag: '🇧🇴', es: "Bolivia", en: "Bolivia", pt: "Bolívia" },
  { code: 'BR', flag: '🇧🇷', es: "Brasil", en: "Brazil", pt: "Brasil" },
  { code: 'BS', flag: '🇧🇸', es: "Bahamas", en: "Bahamas", pt: "Bahamas" },
  { code: 'BT', flag: '🇧🇹', es: "Bután", en: "Bhutan", pt: "Butão" },
  { code: 'BW', flag: '🇧🇼', es: "Botsuana", en: "Botswana", pt: "Botsuana" },
  { code: 'BY', flag: '🇧🇾', es: "Bielorrusia", en: "Belarus", pt: "Bielorrússia" },
  { code: 'BZ', flag: '🇧🇿', es: "Belice", en: "Belize", pt: "Belize" },
  { code: 'CA', flag: '🇨🇦', es: "Canadá", en: "Canada", pt: "Canadá" },
  { code: 'CD', flag: '🇨🇩', es: "República Democrática del Congo", en: "Congo - Kinshasa", pt: "Congo - Kinshasa" },
  { code: 'CF', flag: '🇨🇫', es: "República Centroafricana", en: "Central African Republic", pt: "República Centro-Africana" },
  { code: 'CG', flag: '🇨🇬', es: "Congo", en: "Congo - Brazzaville", pt: "República do Congo" },
  { code: 'CH', flag: '🇨🇭', es: "Suiza", en: "Switzerland", pt: "Suíça" },
  { code: 'CI', flag: '🇨🇮', es: "Côte d’Ivoire", en: "Côte d’Ivoire", pt: "Costa do Marfim" },
  { code: 'CL', flag: '🇨🇱', es: "Chile", en: "Chile", pt: "Chile" },
  { code: 'CM', flag: '🇨🇲', es: "Camerún", en: "Cameroon", pt: "Camarões" },
  { code: 'CN', flag: '🇨🇳', es: "China", en: "China", pt: "China" },
  { code: 'CO', flag: '🇨🇴', es: "Colombia", en: "Colombia", pt: "Colômbia" },
  { code: 'CR', flag: '🇨🇷', es: "Costa Rica", en: "Costa Rica", pt: "Costa Rica" },
  { code: 'CU', flag: '🇨🇺', es: "Cuba", en: "Cuba", pt: "Cuba" },
  { code: 'CV', flag: '🇨🇻', es: "Cabo Verde", en: "Cape Verde", pt: "Cabo Verde" },
  { code: 'CY', flag: '🇨🇾', es: "Chipre", en: "Cyprus", pt: "Chipre" },
  { code: 'CZ', flag: '🇨🇿', es: "Chequia", en: "Czechia", pt: "Tchéquia" },
  { code: 'DE', flag: '🇩🇪', es: "Alemania", en: "Germany", pt: "Alemanha" },
  { code: 'DJ', flag: '🇩🇯', es: "Yibuti", en: "Djibouti", pt: "Djibuti" },
  { code: 'DK', flag: '🇩🇰', es: "Dinamarca", en: "Denmark", pt: "Dinamarca" },
  { code: 'DM', flag: '🇩🇲', es: "Dominica", en: "Dominica", pt: "Dominica" },
  { code: 'DO', flag: '🇩🇴', es: "República Dominicana", en: "Dominican Republic", pt: "República Dominicana" },
  { code: 'DZ', flag: '🇩🇿', es: "Argelia", en: "Algeria", pt: "Argélia" },
  { code: 'EC', flag: '🇪🇨', es: "Ecuador", en: "Ecuador", pt: "Equador" },
  { code: 'EE', flag: '🇪🇪', es: "Estonia", en: "Estonia", pt: "Estônia" },
  { code: 'EG', flag: '🇪🇬', es: "Egipto", en: "Egypt", pt: "Egito" },
  { code: 'ER', flag: '🇪🇷', es: "Eritrea", en: "Eritrea", pt: "Eritreia" },
  { code: 'ES', flag: '🇪🇸', es: "España", en: "Spain", pt: "Espanha" },
  { code: 'ET', flag: '🇪🇹', es: "Etiopía", en: "Ethiopia", pt: "Etiópia" },
  { code: 'FI', flag: '🇫🇮', es: "Finlandia", en: "Finland", pt: "Finlândia" },
  { code: 'FJ', flag: '🇫🇯', es: "Fiyi", en: "Fiji", pt: "Fiji" },
  { code: 'FR', flag: '🇫🇷', es: "Francia", en: "France", pt: "França" },
  { code: 'GA', flag: '🇬🇦', es: "Gabón", en: "Gabon", pt: "Gabão" },
  { code: 'GB', flag: '🇬🇧', es: "Reino Unido", en: "United Kingdom", pt: "Reino Unido" },
  { code: 'GD', flag: '🇬🇩', es: "Granada", en: "Grenada", pt: "Granada" },
  { code: 'GE', flag: '🇬🇪', es: "Georgia", en: "Georgia", pt: "Geórgia" },
  { code: 'GH', flag: '🇬🇭', es: "Ghana", en: "Ghana", pt: "Gana" },
  { code: 'GM', flag: '🇬🇲', es: "Gambia", en: "Gambia", pt: "Gâmbia" },
  { code: 'GN', flag: '🇬🇳', es: "Guinea", en: "Guinea", pt: "Guiné" },
  { code: 'GQ', flag: '🇬🇶', es: "Guinea Ecuatorial", en: "Equatorial Guinea", pt: "Guiné Equatorial" },
  { code: 'GR', flag: '🇬🇷', es: "Grecia", en: "Greece", pt: "Grécia" },
  { code: 'GT', flag: '🇬🇹', es: "Guatemala", en: "Guatemala", pt: "Guatemala" },
  { code: 'GW', flag: '🇬🇼', es: "Guinea-Bisáu", en: "Guinea-Bissau", pt: "Guiné-Bissau" },
  { code: 'GY', flag: '🇬🇾', es: "Guyana", en: "Guyana", pt: "Guiana" },
  { code: 'HK', flag: '🇭🇰', es: "RAE de Hong Kong (China)", en: "Hong Kong SAR China", pt: "Hong Kong, RAE da China" },
  { code: 'HN', flag: '🇭🇳', es: "Honduras", en: "Honduras", pt: "Honduras" },
  { code: 'HR', flag: '🇭🇷', es: "Croacia", en: "Croatia", pt: "Croácia" },
  { code: 'HT', flag: '🇭🇹', es: "Haití", en: "Haiti", pt: "Haiti" },
  { code: 'HU', flag: '🇭🇺', es: "Hungría", en: "Hungary", pt: "Hungria" },
  { code: 'ID', flag: '🇮🇩', es: "Indonesia", en: "Indonesia", pt: "Indonésia" },
  { code: 'IE', flag: '🇮🇪', es: "Irlanda", en: "Ireland", pt: "Irlanda" },
  { code: 'IL', flag: '🇮🇱', es: "Israel", en: "Israel", pt: "Israel" },
  { code: 'IN', flag: '🇮🇳', es: "India", en: "India", pt: "Índia" },
  { code: 'IQ', flag: '🇮🇶', es: "Irak", en: "Iraq", pt: "Iraque" },
  { code: 'IR', flag: '🇮🇷', es: "Irán", en: "Iran", pt: "Irã" },
  { code: 'IS', flag: '🇮🇸', es: "Islandia", en: "Iceland", pt: "Islândia" },
  { code: 'IT', flag: '🇮🇹', es: "Italia", en: "Italy", pt: "Itália" },
  { code: 'JM', flag: '🇯🇲', es: "Jamaica", en: "Jamaica", pt: "Jamaica" },
  { code: 'JO', flag: '🇯🇴', es: "Jordania", en: "Jordan", pt: "Jordânia" },
  { code: 'JP', flag: '🇯🇵', es: "Japón", en: "Japan", pt: "Japão" },
  { code: 'KE', flag: '🇰🇪', es: "Kenia", en: "Kenya", pt: "Quênia" },
  { code: 'KG', flag: '🇰🇬', es: "Kirguistán", en: "Kyrgyzstan", pt: "Quirguistão" },
  { code: 'KH', flag: '🇰🇭', es: "Camboya", en: "Cambodia", pt: "Camboja" },
  { code: 'KM', flag: '🇰🇲', es: "Comoras", en: "Comoros", pt: "Comores" },
  { code: 'KN', flag: '🇰🇳', es: "San Cristóbal y Nieves", en: "St. Kitts & Nevis", pt: "São Cristóvão e Névis" },
  { code: 'KP', flag: '🇰🇵', es: "Corea del Norte", en: "North Korea", pt: "Coreia do Norte" },
  { code: 'KR', flag: '🇰🇷', es: "Corea del Sur", en: "South Korea", pt: "Coreia do Sul" },
  { code: 'KW', flag: '🇰🇼', es: "Kuwait", en: "Kuwait", pt: "Kuwait" },
  { code: 'KZ', flag: '🇰🇿', es: "Kazajistán", en: "Kazakhstan", pt: "Cazaquistão" },
  { code: 'LA', flag: '🇱🇦', es: "Laos", en: "Laos", pt: "Laos" },
  { code: 'LB', flag: '🇱🇧', es: "Líbano", en: "Lebanon", pt: "Líbano" },
  { code: 'LC', flag: '🇱🇨', es: "Santa Lucía", en: "St. Lucia", pt: "Santa Lúcia" },
  { code: 'LI', flag: '🇱🇮', es: "Liechtenstein", en: "Liechtenstein", pt: "Liechtenstein" },
  { code: 'LK', flag: '🇱🇰', es: "Sri Lanka", en: "Sri Lanka", pt: "Sri Lanka" },
  { code: 'LR', flag: '🇱🇷', es: "Liberia", en: "Liberia", pt: "Libéria" },
  { code: 'LS', flag: '🇱🇸', es: "Lesoto", en: "Lesotho", pt: "Lesoto" },
  { code: 'LT', flag: '🇱🇹', es: "Lituania", en: "Lithuania", pt: "Lituânia" },
  { code: 'LU', flag: '🇱🇺', es: "Luxemburgo", en: "Luxembourg", pt: "Luxemburgo" },
  { code: 'LV', flag: '🇱🇻', es: "Letonia", en: "Latvia", pt: "Letônia" },
  { code: 'LY', flag: '🇱🇾', es: "Libia", en: "Libya", pt: "Líbia" },
  { code: 'MA', flag: '🇲🇦', es: "Marruecos", en: "Morocco", pt: "Marrocos" },
  { code: 'MC', flag: '🇲🇨', es: "Mónaco", en: "Monaco", pt: "Mônaco" },
  { code: 'MD', flag: '🇲🇩', es: "Moldavia", en: "Moldova", pt: "Moldávia" },
  { code: 'ME', flag: '🇲🇪', es: "Montenegro", en: "Montenegro", pt: "Montenegro" },
  { code: 'MG', flag: '🇲🇬', es: "Madagascar", en: "Madagascar", pt: "Madagascar" },
  { code: 'MK', flag: '🇲🇰', es: "Macedonia del Norte", en: "North Macedonia", pt: "Macedônia do Norte" },
  { code: 'ML', flag: '🇲🇱', es: "Mali", en: "Mali", pt: "Mali" },
  { code: 'MM', flag: '🇲🇲', es: "Myanmar (Birmania)", en: "Myanmar (Burma)", pt: "Mianmar (Birmânia)" },
  { code: 'MN', flag: '🇲🇳', es: "Mongolia", en: "Mongolia", pt: "Mongólia" },
  { code: 'MO', flag: '🇲🇴', es: "RAE de Macao (China)", en: "Macao SAR China", pt: "Macau, RAE da China" },
  { code: 'MR', flag: '🇲🇷', es: "Mauritania", en: "Mauritania", pt: "Mauritânia" },
  { code: 'MT', flag: '🇲🇹', es: "Malta", en: "Malta", pt: "Malta" },
  { code: 'MU', flag: '🇲🇺', es: "Mauricio", en: "Mauritius", pt: "Maurício" },
  { code: 'MV', flag: '🇲🇻', es: "Maldivas", en: "Maldives", pt: "Maldivas" },
  { code: 'MW', flag: '🇲🇼', es: "Malaui", en: "Malawi", pt: "Malaui" },
  { code: 'MX', flag: '🇲🇽', es: "México", en: "Mexico", pt: "México" },
  { code: 'MY', flag: '🇲🇾', es: "Malasia", en: "Malaysia", pt: "Malásia" },
  { code: 'MZ', flag: '🇲🇿', es: "Mozambique", en: "Mozambique", pt: "Moçambique" },
  { code: 'NA', flag: '🇳🇦', es: "Namibia", en: "Namibia", pt: "Namíbia" },
  { code: 'NE', flag: '🇳🇪', es: "Níger", en: "Niger", pt: "Níger" },
  { code: 'NG', flag: '🇳🇬', es: "Nigeria", en: "Nigeria", pt: "Nigéria" },
  { code: 'NI', flag: '🇳🇮', es: "Nicaragua", en: "Nicaragua", pt: "Nicarágua" },
  { code: 'NL', flag: '🇳🇱', es: "Países Bajos", en: "Netherlands", pt: "Países Baixos" },
  { code: 'NO', flag: '🇳🇴', es: "Noruega", en: "Norway", pt: "Noruega" },
  { code: 'NP', flag: '🇳🇵', es: "Nepal", en: "Nepal", pt: "Nepal" },
  { code: 'NZ', flag: '🇳🇿', es: "Nueva Zelanda", en: "New Zealand", pt: "Nova Zelândia" },
  { code: 'OM', flag: '🇴🇲', es: "Omán", en: "Oman", pt: "Omã" },
  { code: 'PA', flag: '🇵🇦', es: "Panamá", en: "Panama", pt: "Panamá" },
  { code: 'PE', flag: '🇵🇪', es: "Perú", en: "Peru", pt: "Peru" },
  { code: 'PG', flag: '🇵🇬', es: "Papúa Nueva Guinea", en: "Papua New Guinea", pt: "Papua-Nova Guiné" },
  { code: 'PH', flag: '🇵🇭', es: "Filipinas", en: "Philippines", pt: "Filipinas" },
  { code: 'PK', flag: '🇵🇰', es: "Pakistán", en: "Pakistan", pt: "Paquistão" },
  { code: 'PL', flag: '🇵🇱', es: "Polonia", en: "Poland", pt: "Polônia" },
  { code: 'PR', flag: '🇵🇷', es: "Puerto Rico", en: "Puerto Rico", pt: "Porto Rico" },
  { code: 'PS', flag: '🇵🇸', es: "Territorios Palestinos", en: "Palestinian Territories", pt: "Territórios palestinos" },
  { code: 'PT', flag: '🇵🇹', es: "Portugal", en: "Portugal", pt: "Portugal" },
  { code: 'PY', flag: '🇵🇾', es: "Paraguay", en: "Paraguay", pt: "Paraguai" },
  { code: 'QA', flag: '🇶🇦', es: "Catar", en: "Qatar", pt: "Catar" },
  { code: 'RO', flag: '🇷🇴', es: "Rumanía", en: "Romania", pt: "Romênia" },
  { code: 'RS', flag: '🇷🇸', es: "Serbia", en: "Serbia", pt: "Sérvia" },
  { code: 'RU', flag: '🇷🇺', es: "Rusia", en: "Russia", pt: "Rússia" },
  { code: 'RW', flag: '🇷🇼', es: "Ruanda", en: "Rwanda", pt: "Ruanda" },
  { code: 'SA', flag: '🇸🇦', es: "Arabia Saudí", en: "Saudi Arabia", pt: "Arábia Saudita" },
  { code: 'SB', flag: '🇸🇧', es: "Islas Salomón", en: "Solomon Islands", pt: "Ilhas Salomão" },
  { code: 'SC', flag: '🇸🇨', es: "Seychelles", en: "Seychelles", pt: "Seicheles" },
  { code: 'SD', flag: '🇸🇩', es: "Sudán", en: "Sudan", pt: "Sudão" },
  { code: 'SE', flag: '🇸🇪', es: "Suecia", en: "Sweden", pt: "Suécia" },
  { code: 'SG', flag: '🇸🇬', es: "Singapur", en: "Singapore", pt: "Singapura" },
  { code: 'SI', flag: '🇸🇮', es: "Eslovenia", en: "Slovenia", pt: "Eslovênia" },
  { code: 'SK', flag: '🇸🇰', es: "Eslovaquia", en: "Slovakia", pt: "Eslováquia" },
  { code: 'SL', flag: '🇸🇱', es: "Sierra Leona", en: "Sierra Leone", pt: "Serra Leoa" },
  { code: 'SM', flag: '🇸🇲', es: "San Marino", en: "San Marino", pt: "San Marino" },
  { code: 'SN', flag: '🇸🇳', es: "Senegal", en: "Senegal", pt: "Senegal" },
  { code: 'SO', flag: '🇸🇴', es: "Somalia", en: "Somalia", pt: "Somália" },
  { code: 'SR', flag: '🇸🇷', es: "Surinam", en: "Suriname", pt: "Suriname" },
  { code: 'SS', flag: '🇸🇸', es: "Sudán del Sur", en: "South Sudan", pt: "Sudão do Sul" },
  { code: 'SV', flag: '🇸🇻', es: "El Salvador", en: "El Salvador", pt: "El Salvador" },
  { code: 'SY', flag: '🇸🇾', es: "Siria", en: "Syria", pt: "Síria" },
  { code: 'SZ', flag: '🇸🇿', es: "Esuatini", en: "Eswatini", pt: "Essuatíni" },
  { code: 'TD', flag: '🇹🇩', es: "Chad", en: "Chad", pt: "Chade" },
  { code: 'TG', flag: '🇹🇬', es: "Togo", en: "Togo", pt: "Togo" },
  { code: 'TH', flag: '🇹🇭', es: "Tailandia", en: "Thailand", pt: "Tailândia" },
  { code: 'TJ', flag: '🇹🇯', es: "Tayikistán", en: "Tajikistan", pt: "Tadjiquistão" },
  { code: 'TL', flag: '🇹🇱', es: "Timor-Leste", en: "Timor-Leste", pt: "Timor-Leste" },
  { code: 'TM', flag: '🇹🇲', es: "Turkmenistán", en: "Turkmenistan", pt: "Turcomenistão" },
  { code: 'TN', flag: '🇹🇳', es: "Túnez", en: "Tunisia", pt: "Tunísia" },
  { code: 'TO', flag: '🇹🇴', es: "Tonga", en: "Tonga", pt: "Tonga" },
  { code: 'TR', flag: '🇹🇷', es: "Turquía", en: "Türkiye", pt: "Turquia" },
  { code: 'TT', flag: '🇹🇹', es: "Trinidad y Tobago", en: "Trinidad & Tobago", pt: "Trinidad e Tobago" },
  { code: 'TW', flag: '🇹🇼', es: "Taiwán", en: "Taiwan", pt: "Taiwan" },
  { code: 'TZ', flag: '🇹🇿', es: "Tanzania", en: "Tanzania", pt: "Tanzânia" },
  { code: 'UA', flag: '🇺🇦', es: "Ucrania", en: "Ukraine", pt: "Ucrânia" },
  { code: 'UG', flag: '🇺🇬', es: "Uganda", en: "Uganda", pt: "Uganda" },
  { code: 'US', flag: '🇺🇸', es: "Estados Unidos", en: "United States", pt: "Estados Unidos" },
  { code: 'UY', flag: '🇺🇾', es: "Uruguay", en: "Uruguay", pt: "Uruguai" },
  { code: 'UZ', flag: '🇺🇿', es: "Uzbekistán", en: "Uzbekistan", pt: "Uzbequistão" },
  { code: 'VA', flag: '🇻🇦', es: "Ciudad del Vaticano", en: "Vatican City", pt: "Cidade do Vaticano" },
  { code: 'VC', flag: '🇻🇨', es: "San Vicente y las Granadinas", en: "St. Vincent & Grenadines", pt: "São Vicente e Granadinas" },
  { code: 'VE', flag: '🇻🇪', es: "Venezuela", en: "Venezuela", pt: "Venezuela" },
  { code: 'VN', flag: '🇻🇳', es: "Vietnam", en: "Vietnam", pt: "Vietnã" },
  { code: 'VU', flag: '🇻🇺', es: "Vanuatu", en: "Vanuatu", pt: "Vanuatu" },
  { code: 'WS', flag: '🇼🇸', es: "Samoa", en: "Samoa", pt: "Samoa" },
  { code: 'XK', flag: '🇽🇰', es: "Kosovo", en: "Kosovo", pt: "Kosovo" },
  { code: 'YE', flag: '🇾🇪', es: "Yemen", en: "Yemen", pt: "Iêmen" },
  { code: 'ZA', flag: '🇿🇦', es: "Sudáfrica", en: "South Africa", pt: "África do Sul" },
  { code: 'ZM', flag: '🇿🇲', es: "Zambia", en: "Zambia", pt: "Zâmbia" },
  { code: 'ZW', flag: '🇿🇼', es: "Zimbabue", en: "Zimbabwe", pt: "Zimbábue" },
];

const BY_CODE = new Map(COUNTRIES.map(c => [c.code, c]));

export function countryByCode(code: string | null | undefined): Country | null {
  if (!code) return null;
  return BY_CODE.get(code.toUpperCase()) ?? null;
}

export function countryName(country: Country, locale: string): string {
  if (locale.startsWith('en')) return country.en;
  if (locale.startsWith('pt')) return country.pt;
  return country.es;
}

/** Busca por nombre en cualquiera de los idiomas, sin acentos ni mayúsculas. */
export function searchCountries(query: string, locale = 'es'): Country[] {
  const q = normalize(query);
  if (!q) return [...COUNTRIES].sort((a, b) => countryName(a, locale).localeCompare(countryName(b, locale)));
  return COUNTRIES
    .filter(c => normalize(c.es).includes(q) || normalize(c.en).includes(q)
              || normalize(c.pt).includes(q) || c.code.toLowerCase() === q)
    .sort((a, b) => countryName(a, locale).localeCompare(countryName(b, locale)));
}

function normalize(s: string): string {
  return s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
}

